language: c

os:
  - linux

before_install:
  - sudo apt-get install -y libev-dev libssl-dev
  - git clone https://github.com/zhaojh329/libuwsc.git
  - cd libuwsc && cmake . && sudo make install && cd -
  - git clone https://github.com/protobuf-c/protobuf-c.git
  - cd protobuf-c && ./autogen.sh && ./configure --disable-protoc && sudo make install && cd -

script:
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
